[mgr]
ratio = [1, 2, 4]
#sort_by = "mtime"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "none"
show_symlink = false
show_hidden = false

[preview]
wrap = "yes"

[[opener.set-wallpaper-all]]
run = '''
for m in $(hyprctl monitors -j | jq -r '.[].name'); do
  hyprctl hyprpaper wallpaper "$m,$1"
done
'''
for = "linux"
desc = "Set as wallpaper, for ALL monitors"

[[opener.set-wallpaper-left]]
run = 'hyprctl hyprpaper wallpaper DP-3,"$1"'
for = "linux"
desc = "Set as wallpaper, for LEFT monitors"

[[opener.set-wallpaper-right]]
run = 'hyprctl hyprpaper wallpaper HDMI-A-1,"$1"'
for = "linux"
desc = "Set as wallpaper, for RIGHT monitors"


[[open.prepend_rules]]
mime = "image/*"
use = ["set-wallpaper-all", "set-wallpaper-left", "set-wallpaper-right", "open"]

## GIT
[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
